---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: # kubeconfig path
    - name: Deploy nginx app 
      k8s:
        src: ~/Demo-projects/Simple-K8s-Files/nginx-config.yaml
        kubeconfig:  # kubeconfig path       
        state: present
        namespace: my-app
