- name: Install python3, docker , docker-compose
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name:
      get_url: 
        url:  https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose

 
  



- name: Create new linux user
  hosts: docker_server
  become: yes
  tasks: 
    - name: Create new linux user
      user:
        name: farah
        groups: adm,docker


- name: Start docker containers
  hosts: docker_server
  become: yes
  become_user: farah
  vars_prompt:
    - name: docker_password
      prompt: Enter password for docker registry
  tasks:
    - name: Copy docker compose
      copy:
        src: /Users/farahomar/Downloads/bootcamp-java-mysql-ansible/docker-compose.yaml
        dest: /home/farah/docker-compose.yaml
    - name: Docker login
      docker_login: 
        registry_url: https://index.docker.io/v1/
        username: fomar123
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose: 
        project_src: /home/farah  
