 - name: Copy docker compose
   copy:
     src: docker-compose-full.yaml
     dest: /home/farah/docker-compose.yaml

 - name: Docker login
   docker_login: 
     registry_url: "{{ docker_registrty }}"
     username: "{{ docker_user }}"
     password: "{{ docker_password }}"

 - name: Start container from compose
   docker_compose: 
     project_src: /home/farah  
